-- 扩充内置赛事目录，并给三级菜单与赛季自动解析提供稳定元数据。

INSERT INTO football.competitions
    (id, code, name, country_code, timezone, competition_kind, metadata)
VALUES
    ('389bb551-9d12-5553-a849-5ccea5afc573', 'FIFA-WORLD-CUP', 'FIFA 世界杯', 'FIFA', 'UTC', 'group_stage', jsonb_build_object('built_in', true, 'scope', 'national', 'menu_region', '世界', 'confederation', 'FIFA', 'season_pattern', 'tournament', 'sort_order', 1000, 'temporary', false)),
    ('0e61e265-2360-5bd2-a450-5c2c3807c13b', 'FIFA-WORLD-CUP-QUAL', '世界杯预选赛（通用）', 'FIFA', 'UTC', 'group_stage', jsonb_build_object('built_in', true, 'scope', 'national', 'menu_region', '世界', 'confederation', 'FIFA', 'season_pattern', 'calendar', 'sort_order', 1010, 'temporary', false)),
    ('ca4a2acd-7acf-54ba-a1bc-ccc893067d26', 'FIFA-FRIENDLY', '国际友谊赛', 'FIFA', 'UTC', 'friendly', jsonb_build_object('built_in', true, 'scope', 'national', 'menu_region', '世界', 'confederation', 'FIFA', 'season_pattern', 'calendar', 'sort_order', 1020, 'temporary', false)),
    ('c1399f50-4812-5d57-99c6-fd056da0a1a7', 'CONMEBOL-COPA-AMERICA', '美洲杯', 'CONMEBOL', 'America/Asuncion', 'group_stage', jsonb_build_object('built_in', true, 'scope', 'national', 'menu_region', '南美洲', 'confederation', 'CONMEBOL', 'season_pattern', 'tournament', 'sort_order', 1030, 'temporary', false)),
    ('e63f6425-589d-5886-a369-283435618d38', 'CONMEBOL-WCQ', '世界杯南美区预选赛', 'CONMEBOL', 'America/Asuncion', 'league', jsonb_build_object('built_in', true, 'scope', 'national', 'menu_region', '南美洲', 'confederation', 'CONMEBOL', 'season_pattern', 'calendar', 'sort_order', 1040, 'temporary', false)),
    ('72d85285-f812-5a72-985e-de0f932e2767', 'AFC-ASIAN-CUP', '亚洲杯', 'AFC', 'Asia/Kuala_Lumpur', 'group_stage', jsonb_build_object('built_in', true, 'scope', 'national', 'menu_region', '亚洲', 'confederation', 'AFC', 'season_pattern', 'tournament', 'sort_order', 1050, 'temporary', false)),
    ('1d32ab26-a162-52e6-8658-ab1ab62f6823', 'AFC-WCQ', '世界杯亚洲区预选赛', 'AFC', 'Asia/Kuala_Lumpur', 'group_stage', jsonb_build_object('built_in', true, 'scope', 'national', 'menu_region', '亚洲', 'confederation', 'AFC', 'season_pattern', 'calendar', 'sort_order', 1060, 'temporary', false)),
    ('25c3a62e-c3ef-55d3-8446-ddffc924dd9a', 'CAF-AFCON', '非洲国家杯', 'CAF', 'Africa/Cairo', 'group_stage', jsonb_build_object('built_in', true, 'scope', 'national', 'menu_region', '非洲', 'confederation', 'CAF', 'season_pattern', 'tournament', 'sort_order', 1070, 'temporary', false)),
    ('7be39070-16d2-51a4-af88-1f4541d88797', 'CAF-WCQ', '世界杯非洲区预选赛', 'CAF', 'Africa/Cairo', 'group_stage', jsonb_build_object('built_in', true, 'scope', 'national', 'menu_region', '非洲', 'confederation', 'CAF', 'season_pattern', 'calendar', 'sort_order', 1080, 'temporary', false)),
    ('74100a1f-c8d8-56f2-9edd-181204315d1e', 'CONCACAF-GOLD-CUP', '中北美及加勒比金杯', 'CONCACAF', 'America/New_York', 'group_stage', jsonb_build_object('built_in', true, 'scope', 'national', 'menu_region', '北中美洲', 'confederation', 'CONCACAF', 'season_pattern', 'tournament', 'sort_order', 1090, 'temporary', false)),
    ('b9fa508f-4746-516b-bfe8-e4a7cf254840', 'CONCACAF-NATIONS-LEAGUE', '中北美及加勒比国家联赛', 'CONCACAF', 'America/New_York', 'group_stage', jsonb_build_object('built_in', true, 'scope', 'national', 'menu_region', '北中美洲', 'confederation', 'CONCACAF', 'season_pattern', 'cross_year', 'sort_order', 1100, 'temporary', false)),
    ('5c82985b-99e9-5b40-a272-92c53a91f988', 'CONCACAF-WCQ', '世界杯中北美区预选赛', 'CONCACAF', 'America/New_York', 'group_stage', jsonb_build_object('built_in', true, 'scope', 'national', 'menu_region', '北中美洲', 'confederation', 'CONCACAF', 'season_pattern', 'calendar', 'sort_order', 1110, 'temporary', false)),
    ('f15206f9-40d1-5525-acd0-73917dd3747d', 'OFC-NATIONS-CUP', '大洋洲国家杯', 'OFC', 'Pacific/Auckland', 'group_stage', jsonb_build_object('built_in', true, 'scope', 'national', 'menu_region', '大洋洲', 'confederation', 'OFC', 'season_pattern', 'tournament', 'sort_order', 1120, 'temporary', false)),
    ('c2168948-0e7d-5671-a0be-b9fe71fa4dbe', 'OFC-WCQ', '世界杯大洋洲区预选赛', 'OFC', 'Pacific/Auckland', 'group_stage', jsonb_build_object('built_in', true, 'scope', 'national', 'menu_region', '大洋洲', 'confederation', 'OFC', 'season_pattern', 'calendar', 'sort_order', 1130, 'temporary', false)),
    ('6bf22acd-75f8-5e64-9f5b-23e7afc5477d', 'CONMEBOL-LIBERTADORES', '南美解放者杯', 'CONMEBOL', 'America/Asuncion', 'custom', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '南美洲', 'confederation', 'CONMEBOL', 'season_pattern', 'calendar', 'sort_order', 1200, 'temporary', false)),
    ('ef7f63a8-cca9-5cca-9a3b-2dd14fb57345', 'CONMEBOL-SUDAMERICANA', '南美俱乐部杯', 'CONMEBOL', 'America/Asuncion', 'custom', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '南美洲', 'confederation', 'CONMEBOL', 'season_pattern', 'calendar', 'sort_order', 1210, 'temporary', false)),
    ('258d4231-496d-5729-a569-c9a555ad8f73', 'CAF-CHAMPIONS-LEAGUE', '非洲冠军联赛', 'CAF', 'Africa/Cairo', 'custom', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '非洲', 'confederation', 'CAF', 'season_pattern', 'cross_year', 'sort_order', 1240, 'temporary', false)),
    ('94cf1318-fe8b-5ddc-9f70-a09d4a5a50b2', 'CAF-CONFEDERATION-CUP', '非洲联盟杯', 'CAF', 'Africa/Cairo', 'custom', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '非洲', 'confederation', 'CAF', 'season_pattern', 'cross_year', 'sort_order', 1250, 'temporary', false)),
    ('3a4520bd-a7e8-53e9-9c0d-396b36c2969b', 'CONCACAF-CHAMPIONS-CUP', '中北美及加勒比冠军杯', 'CONCACAF', 'America/New_York', 'custom', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '北中美洲', 'confederation', 'CONCACAF', 'season_pattern', 'calendar', 'sort_order', 1260, 'temporary', false)),
    ('a9516379-1544-53e6-963d-57f7ed6964ff', 'FIFA-CLUB-WORLD-CUP', 'FIFA 俱乐部世界杯', 'FIFA', 'UTC', 'group_stage', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '世界', 'confederation', 'FIFA', 'season_pattern', 'tournament', 'sort_order', 1270, 'temporary', false)),
    ('85aecce9-c8da-5b60-b211-0dd2d77884ec', 'ES-LALIGA', '西班牙甲级联赛', 'ES', 'Europe/Madrid', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '西班牙', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2220, 'temporary', false)),
    ('5ea01bdc-e42f-54e5-a452-6977f0db2cd2', 'ES-SEGUNDA', '西班牙乙级联赛', 'ES', 'Europe/Madrid', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '西班牙', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2230, 'temporary', false)),
    ('64a6b5a2-8788-59a9-a3b7-58ea00c525d8', 'ES-COPA-DEL-REY', '西班牙国王杯', 'ES', 'Europe/Madrid', 'knockout_single_leg', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '西班牙', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2240, 'temporary', false)),
    ('49d7eaa4-ea30-5aba-bd4a-c6c1223ac4d3', 'DE-BUNDESLIGA', '德国甲级联赛', 'DE', 'Europe/Berlin', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '德国', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2250, 'temporary', false)),
    ('b3301321-0db6-5cd3-b9a4-0e3cfd3b5c14', 'DE-2-BUNDESLIGA', '德国乙级联赛', 'DE', 'Europe/Berlin', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '德国', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2260, 'temporary', false)),
    ('001bdabf-6ede-56ae-b057-e6eeaa100c18', 'DE-DFB-POKAL', '德国杯', 'DE', 'Europe/Berlin', 'knockout_single_leg', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '德国', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2270, 'temporary', false)),
    ('fbb20a60-2f29-525f-ad5c-e3dca1dd638f', 'IT-SERIE-A', '意大利甲级联赛', 'IT', 'Europe/Rome', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '意大利', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2280, 'temporary', false)),
    ('b17b26bf-fb6d-5650-b078-71f59b28c168', 'IT-SERIE-B', '意大利乙级联赛', 'IT', 'Europe/Rome', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '意大利', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2290, 'temporary', false)),
    ('10cc5bbc-49b5-549e-ba25-3feb6df91841', 'IT-COPPA-ITALIA', '意大利杯', 'IT', 'Europe/Rome', 'knockout_single_leg', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '意大利', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2300, 'temporary', false)),
    ('828f2304-01c9-50ec-83e7-1e1bad8d863f', 'FR-LIGUE-1', '法国甲级联赛', 'FR', 'Europe/Paris', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '法国', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2310, 'temporary', false)),
    ('be4b3d11-7a56-5e95-8ead-6287d2ec9d72', 'FR-LIGUE-2', '法国乙级联赛', 'FR', 'Europe/Paris', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '法国', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2320, 'temporary', false)),
    ('7affd0a7-c490-5572-bd00-332389c62e45', 'FR-COUPE-DE-FRANCE', '法国杯', 'FR', 'Europe/Paris', 'knockout_single_leg', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '法国', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2330, 'temporary', false)),
    ('2b686d74-5595-559f-95db-39c63df741e1', 'NL-EREDIVISIE', '荷兰甲级联赛', 'NL', 'Europe/Amsterdam', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '荷兰', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2340, 'temporary', false)),
    ('3c80043d-b3db-55a1-88d0-eaf5de8b4591', 'NL-EERSTE-DIVISIE', '荷兰乙级联赛', 'NL', 'Europe/Amsterdam', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '荷兰', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2350, 'temporary', false)),
    ('49c73a0f-eaa4-53a7-b111-40e7666bed9e', 'NL-KNVB-CUP', '荷兰杯', 'NL', 'Europe/Amsterdam', 'knockout_single_leg', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '荷兰', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2360, 'temporary', false)),
    ('f9184beb-a22a-5979-9326-a1882a197bd2', 'PT-PRIMEIRA-LIGA', '葡萄牙超级联赛', 'PT', 'Europe/Lisbon', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '葡萄牙', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2370, 'temporary', false)),
    ('2dded488-ffb7-5d23-b6ab-03bca4235b88', 'PT-LIGA-2', '葡萄牙甲级联赛', 'PT', 'Europe/Lisbon', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '葡萄牙', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2380, 'temporary', false)),
    ('67578072-d9ac-563e-a1ac-3e354a27bd8c', 'PT-TACA', '葡萄牙杯', 'PT', 'Europe/Lisbon', 'knockout_single_leg', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '葡萄牙', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2390, 'temporary', false)),
    ('1afcbf9b-6a39-5170-8c4f-f816cabe66b8', 'BE-PRO-LEAGUE', '比利时甲级联赛', 'BE', 'Europe/Brussels', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '比利时', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2400, 'temporary', false)),
    ('04bc5760-3620-5b94-bb6e-9a486d98bc2e', 'BE-CUP', '比利时杯', 'BE', 'Europe/Brussels', 'knockout_single_leg', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '比利时', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2410, 'temporary', false)),
    ('befdafe9-241c-573d-810f-8bca7249347a', 'SCO-PREMIERSHIP', '苏格兰超级联赛', 'GB', 'Europe/London', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '苏格兰', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2420, 'temporary', false)),
    ('46c8f11e-8abd-5aa3-8c27-87c4d53dfde7', 'SCO-CUP', '苏格兰杯', 'GB', 'Europe/London', 'knockout_single_leg', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '苏格兰', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2430, 'temporary', false)),
    ('744adcc1-faa3-5d99-9671-56856a7826c9', 'AT-BUNDESLIGA', '奥地利甲级联赛', 'AT', 'Europe/Vienna', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '奥地利', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2440, 'temporary', false)),
    ('729157e4-c8c8-5c17-90fb-79445c4245e6', 'TR-SUPER-LIG', '土耳其超级联赛', 'TR', 'Europe/Istanbul', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '土耳其', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2450, 'temporary', false)),
    ('ca210fbe-51db-5bb8-b9eb-840930e49632', 'GR-SUPER-LEAGUE', '希腊超级联赛', 'GR', 'Europe/Athens', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '希腊', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2460, 'temporary', false)),
    ('430f6fcf-174a-5073-acf2-07fcc3215a0b', 'CZ-FIRST-LEAGUE', '捷克甲级联赛', 'CZ', 'Europe/Prague', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '捷克', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2470, 'temporary', false)),
    ('9b51fdb7-cca1-5705-98d7-50be949b2572', 'PL-EKSTRAKLASA', '波兰甲级联赛', 'PL', 'Europe/Warsaw', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '波兰', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2480, 'temporary', false)),
    ('ed8c6645-1edd-5217-b07f-8f9a697b41f2', 'SE-ALLSVENSKAN', '瑞典超级联赛', 'SE', 'Europe/Stockholm', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '瑞典', 'confederation', 'UEFA', 'season_pattern', 'calendar', 'sort_order', 2490, 'temporary', false)),
    ('1a19839d-29c5-5492-94bb-5f08ea0c2403', 'SE-SUPERETTAN', '瑞典甲级联赛', 'SE', 'Europe/Stockholm', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '瑞典', 'confederation', 'UEFA', 'season_pattern', 'calendar', 'sort_order', 2500, 'temporary', false)),
    ('d8663641-1f19-52a0-95b0-9ef265b5597a', 'SE-CUP', '瑞典杯', 'SE', 'Europe/Stockholm', 'knockout_single_leg', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '瑞典', 'confederation', 'UEFA', 'season_pattern', 'calendar', 'sort_order', 2510, 'temporary', false)),
    ('ea8a85b1-71be-594d-b2ec-06da510cd856', 'DK-SUPERLIGA', '丹麦超级联赛', 'DK', 'Europe/Copenhagen', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '丹麦', 'confederation', 'UEFA', 'season_pattern', 'cross_year', 'sort_order', 2520, 'temporary', false)),
    ('7934c5d2-d83d-5aac-ac6c-91cd046846b2', 'IS-BESTA-DEILD', '冰岛超级联赛', 'IS', 'Atlantic/Reykjavik', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '冰岛', 'confederation', 'UEFA', 'season_pattern', 'calendar', 'sort_order', 2530, 'temporary', false)),
    ('928c86bf-5c3c-540a-9e30-047a59cf29f3', 'US-MLS', '美国职业足球大联盟', 'US', 'America/New_York', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '美国', 'confederation', 'CONCACAF', 'season_pattern', 'calendar', 'sort_order', 4540, 'temporary', false)),
    ('0796a984-2bee-5958-a76c-78d7add3c1b4', 'US-US-OPEN-CUP', '美国公开杯', 'US', 'America/New_York', 'knockout_single_leg', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '美国', 'confederation', 'CONCACAF', 'season_pattern', 'calendar', 'sort_order', 4550, 'temporary', false)),
    ('1d5466bf-d8e0-5716-942f-e04d35cced81', 'MX-LIGA-MX', '墨西哥超级联赛', 'MX', 'America/Mexico_City', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '墨西哥', 'confederation', 'CONCACAF', 'season_pattern', 'split', 'sort_order', 4560, 'temporary', false)),
    ('582c21e1-db3d-54fe-9a3a-a25d8219b7da', 'MX-COPA', '墨西哥杯', 'MX', 'America/Mexico_City', 'knockout_single_leg', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '墨西哥', 'confederation', 'CONCACAF', 'season_pattern', 'split', 'sort_order', 4570, 'temporary', false)),
    ('f8c5751c-22b5-5612-be56-af4927269ef5', 'BR-SERIE-A', '巴西甲级联赛', 'BR', 'America/Sao_Paulo', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '巴西', 'confederation', 'CONMEBOL', 'season_pattern', 'calendar', 'sort_order', 4580, 'temporary', false)),
    ('4f21d5ef-837d-5e28-82d9-385b9fd91e4b', 'BR-SERIE-B', '巴西乙级联赛', 'BR', 'America/Sao_Paulo', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '巴西', 'confederation', 'CONMEBOL', 'season_pattern', 'calendar', 'sort_order', 4590, 'temporary', false)),
    ('4d19a378-374a-5844-ac86-053e4f617e42', 'BR-COPA-DO-BRASIL', '巴西杯', 'BR', 'America/Sao_Paulo', 'knockout_single_leg', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '巴西', 'confederation', 'CONMEBOL', 'season_pattern', 'calendar', 'sort_order', 4600, 'temporary', false)),
    ('e19942a7-5724-5692-9146-5c928dc6d1bc', 'AR-PRIMERA', '阿根廷甲级联赛', 'AR', 'America/Argentina/Buenos_Aires', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '阿根廷', 'confederation', 'CONMEBOL', 'season_pattern', 'calendar', 'sort_order', 4610, 'temporary', false)),
    ('e7654178-abcf-5eb9-8e18-8e9044c19b18', 'AR-COPA-ARGENTINA', '阿根廷杯', 'AR', 'America/Argentina/Buenos_Aires', 'knockout_single_leg', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '阿根廷', 'confederation', 'CONMEBOL', 'season_pattern', 'calendar', 'sort_order', 4620, 'temporary', false)),
    ('5810deaf-c5bf-521a-a13e-066d728234a9', 'CO-PRIMERA-A', '哥伦比亚甲级联赛', 'CO', 'America/Bogota', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '哥伦比亚', 'confederation', 'CONMEBOL', 'season_pattern', 'split', 'sort_order', 4630, 'temporary', false)),
    ('bb25171e-1f12-532f-b40c-22542b3c8ba4', 'CL-PRIMERA', '智利甲级联赛', 'CL', 'America/Santiago', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '智利', 'confederation', 'CONMEBOL', 'season_pattern', 'calendar', 'sort_order', 4640, 'temporary', false)),
    ('c0c37dc9-8be6-58d9-a528-658f5117f712', 'UY-PRIMERA', '乌拉圭甲级联赛', 'UY', 'America/Montevideo', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '乌拉圭', 'confederation', 'CONMEBOL', 'season_pattern', 'calendar', 'sort_order', 4650, 'temporary', false)),
    ('ff80126c-2df5-518f-93c9-f2c0c82c2ad2', 'CN-CSL', '中国足球超级联赛', 'CN', 'Asia/Shanghai', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '中国', 'confederation', 'AFC', 'season_pattern', 'calendar', 'sort_order', 6660, 'temporary', false)),
    ('204e8f76-dc09-5ca9-808f-e7592cc2b0a1', 'CN-LEAGUE-ONE', '中国足球甲级联赛', 'CN', 'Asia/Shanghai', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '中国', 'confederation', 'AFC', 'season_pattern', 'calendar', 'sort_order', 6670, 'temporary', false)),
    ('f38a4301-7518-55a4-b81f-833638d618f6', 'CN-FA-CUP', '中国足协杯', 'CN', 'Asia/Shanghai', 'knockout_single_leg', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '中国', 'confederation', 'AFC', 'season_pattern', 'calendar', 'sort_order', 6680, 'temporary', false)),
    ('a0cedc25-d893-5037-b12f-0c63d177d7e4', 'SA-PRO-LEAGUE', '沙特职业联赛', 'SA', 'Asia/Riyadh', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '沙特阿拉伯', 'confederation', 'AFC', 'season_pattern', 'cross_year', 'sort_order', 6690, 'temporary', false)),
    ('0f728c56-a2b8-5cd2-a703-92e7fac96896', 'SA-KING-CUP', '沙特国王杯', 'SA', 'Asia/Riyadh', 'knockout_single_leg', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '沙特阿拉伯', 'confederation', 'AFC', 'season_pattern', 'cross_year', 'sort_order', 6700, 'temporary', false)),
    ('68063ea8-65d2-5308-873d-9459f163c121', 'AU-A-LEAGUE', '澳大利亚超级联赛', 'AU', 'Australia/Sydney', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '澳大利亚', 'confederation', 'AFC', 'season_pattern', 'cross_year', 'sort_order', 6710, 'temporary', false)),
    ('e5c1599e-3e7d-5c40-84a9-c4ab04f7e20e', 'QA-STARS-LEAGUE', '卡塔尔星级联赛', 'QA', 'Asia/Qatar', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '卡塔尔', 'confederation', 'AFC', 'season_pattern', 'cross_year', 'sort_order', 6720, 'temporary', false)),
    ('117a83e6-573d-5d39-827c-81a4bd24b303', 'AE-PRO-LEAGUE', '阿联酋职业联赛', 'AE', 'Asia/Dubai', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '阿联酋', 'confederation', 'AFC', 'season_pattern', 'cross_year', 'sort_order', 6730, 'temporary', false)),
    ('f2f624c5-dd5d-50d3-b16a-6b8e1134e0db', 'EG-PREMIER-LEAGUE', '埃及超级联赛', 'EG', 'Africa/Cairo', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '埃及', 'confederation', 'CAF', 'season_pattern', 'cross_year', 'sort_order', 6740, 'temporary', false)),
    ('ff9b308b-03bd-57af-ad24-b041f2290084', 'MA-BOTOLA', '摩洛哥甲级联赛', 'MA', 'Africa/Casablanca', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '摩洛哥', 'confederation', 'CAF', 'season_pattern', 'cross_year', 'sort_order', 6750, 'temporary', false)),
    ('a6791837-019e-5f4e-824e-266a90bf00aa', 'ZA-PSL', '南非超级联赛', 'ZA', 'Africa/Johannesburg', 'league', jsonb_build_object('built_in', true, 'scope', 'club', 'menu_region', '南非', 'confederation', 'CAF', 'season_pattern', 'cross_year', 'sort_order', 6760, 'temporary', false))
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    country_code = EXCLUDED.country_code,
    timezone = EXCLUDED.timezone,
    competition_kind = EXCLUDED.competition_kind,
    is_active = true,
    metadata = football.competitions.metadata || EXCLUDED.metadata,
    updated_at = now();

-- 旧内置目录补齐三级菜单和赛季模式，保留原有ID及所有引用。
UPDATE football.competitions
SET metadata = metadata || jsonb_build_object(
        'scope', CASE
            WHEN code IN ('UEFA-NATIONS-LEAGUE','UEFA-EURO','UEFA-EURO-QUAL','UEFA-WCQ') THEN 'national'
            WHEN code = 'GENERIC-FRIENDLY' THEN 'other'
            ELSE 'club'
        END,
        'menu_region', COALESCE(NULLIF(metadata->>'menu_region',''), NULLIF(metadata->>'region',''), country_code, '其他'),
        'confederation', COALESCE(NULLIF(metadata->>'confederation',''), CASE
            WHEN country_code IN ('UEFA','GB','ES','DE','IT','FR','NL','PT','BE','TR','CH','NO','FI','SE','DK','AT','GR','CZ','PL','IS') THEN 'UEFA'
            WHEN country_code IN ('AFC','KR','JP','CN','SA','AU','QA','AE') THEN 'AFC'
            WHEN country_code IN ('CONMEBOL','BR','AR','CO','CL','UY') THEN 'CONMEBOL'
            WHEN country_code IN ('CONCACAF','US','MX','CA') THEN 'CONCACAF'
            WHEN country_code IN ('CAF','EG','MA','ZA') THEN 'CAF'
            ELSE 'FIFA' END),
        'season_pattern', COALESCE(NULLIF(metadata->>'season_pattern',''), CASE
            WHEN country_code IN ('KR','JP','FI','NO','SE','IS','US','BR','AR','CO','CL','UY','CN') THEN 'calendar'
            WHEN code LIKE 'GENERIC-%' THEN 'calendar'
            ELSE 'cross_year' END)
    ),
    updated_at = now()
WHERE COALESCE((metadata->>'built_in')::boolean, false);
