from pathlib import Path

path = Path("docs/modular-rewrite/R04-persistence-foundation/R04-04-port-adapter-注册.md")
text = path.read_text(encoding="utf-8")
anchor = "## 验证\n\n"
insert = (
    "## 验证\n\n"
    "- 首次 implementation run `31686470233`：起点保护范围通过；实施 helper 在切换 Application adapters 时发现 `analytics.rs` 存在多行 `self\\n.transition_store()` 形式，生成器只覆盖单行形式后主动 fail-fast。最小门禁、阶段回归、文档与提交步骤均未执行，远端未产生任何生产源码提交。恢复 helper 改为同时规范单行/多行转发，并从基线重新生成全部 adapter 变更。\n"
    "- 第二次 implementation run `31686662626`：起点保护范围与规范化 adapter 生成已完成，`write_verifier_and_package()` 也实际成功；临时 runner 却因控制流保护错误，把“无需 fallback”误判为异常并主动 fail-fast。最小门禁、阶段回归、文档与提交步骤仍未执行，远端仍无生产源码提交。恢复只移除该错误 guard，成功路径直接继续，fallback 仍仅捕获唯一已知 package anchor mismatch，其他异常继续硬失败。\n"
    "- 第三次 implementation run `31686951586`：Apply 已成功并首次进入真正最小门禁；`verify:persistence-adapters` 先行失败，原因是 verifier 用单行字符串匹配 `register_adapters(options).await.map_err(...)`，而 rustfmt 将相同调用链格式化为多行。该 run 在专项静态门禁即 fail-fast，R4-01/R4-02/R4-03 后续门禁、Rust compile/tests、stage regression、文档与提交均未执行。恢复仅将此断言改为格式无关正则，不修改生产注册实现、不降低语义检查。\n"
    "- 第四次 implementation run `31687122419`：R4-04 专项及 R4-01/R4-02/R4-03 回归均已通过；数据库 baseline 随后检测到本节点合法修改的 `crates/persistence-postgres/src/store/postgres_store.rs` runtime-source Git blob 指纹从 `939445bec1e0e35ab28c25173d87e2ccf4dc79de` 变化而 fail-fast。Rust compile/tests 与 stage regression 尚未执行，远端仍无生产源码提交。R4-01 已建立对合法 Persistence runtime 重构同步 `architecture/database-baseline.json` 的先例；恢复仅在 rustfmt 后重新计算并替换该单一 runtime-source 指纹，46 个 migration SQL、migration aggregate、integration test 集合和其他 runtime-source 指纹保持冻结。\n"
    "- 第五次 implementation run `31687372054`：R4-04 专项、R4-01/R4-02/R4-03 回归、数据库 baseline、保护资产、rustfmt 均已通过，并首次进入 `cargo check -p football-persistence-postgres -p football-application`。Application 编译暴露 4 个 wrapper 移除后的解析边界错误：`map_persistence_error` 仅为 adapters-parent 可见，不能供 sibling `port_registry` 使用；以及 `PostgresStore` inherent `close() -> ()` 优先于 `DatabaseLifecyclePort::close() -> PortResult<()>`，使 `activate/disconnect` 两处 `?` 无法应用。Persistence/Application tests 与 stage regression 因 compile fail-fast 未执行，远端仍无生产源码提交。恢复将 error mapper 精确限制为 `pub(in crate::composition)`，并在 `DatabaseService` 两个需要传播结果的关闭路径显式调用 `DatabaseLifecyclePort::close(&store)`，保持原 PortResult/错误传播语义；专项 verifier 同步锁定这两个兼容约束。\n"
    "- 第六次 implementation run `31687732166`：R4-04 最小硬门禁完整通过：R4-04/R4-01/R4-02/R4-03 专项、数据库 baseline/保护资产、rustfmt、Persistence+Application `cargo check`、Persistence 80/80 unit tests、Application 33/33 tests 均通过；18 个 PostgreSQL integration tests 仍按契约为 ignored，未执行。阶段回归随后执行 `npm run setup` 并进入 `verify:architecture`，模块边界、状态所有权、受保护导入、Domain inventory/root exports、Application Ports 均通过，但旧 `verify-database-service.mjs` 仍以 `ActiveDatabase` 字面类型和旧 `port_registry.rs` impl 位置断言 DatabaseService/DatabaseLifecyclePort/DatabaseObservabilityPort，因 R4-04 合法 owner 迁移而 fail-fast；`verify:frontend`、workspace Clippy/tests 未执行，远端仍无生产源码提交。恢复不删除或放宽 Database Service gate，而是将其精确迁移到 `DatabaseService.session: PersistenceStore`、`composition/adapters/database.rs` 的 Lifecycle/Observability impl 与 `port_registry.rs` 的 `register_adapters` composition 入口，并继续拒绝 ApplicationService 直接持有活动数据库槽位。\n"
    "- 第七次 implementation run `31688354846`：最小硬门禁再次完整通过，迁移后的 Database Service gate 也已通过；`verify:architecture` 继续到 Competition/Rules Service 时，旧 `verify-competition-rules-service.mjs` 仍要求三个 Port `for ActiveDatabase` 且位于 `port_registry.rs`，因此 fail-fast。`verify:frontend`、workspace Clippy/tests、frozen/docs/commit 未执行，远端仍无生产源码提交。为避免同类旧 owner 假设逐个串行暴露，追加 scope audit run `31688840100`，一次性扫描 `scripts/`：除已迁移 Database gate 外，共 11 个 verifier 仍含 `ActiveDatabase` 正向 adapter-owner 断言。恢复使用严格 allowlist 同步迁移这 11 个 owner 断言到 `PersistenceStore`/现有具名 adapter 文件；service/use-case 中禁止 `PersistenceStore`/`football_persistence_postgres` 泄漏以及禁止 `transition_store` 的负向约束全部保持不变。\n\n"
)
if text.count(anchor) != 1:
    raise RuntimeError(f"R4-04 verification anchor expected once, found {text.count(anchor)}")
text = text.replace(anchor, insert, 1)
path.write_text(text, encoding="utf-8", newline="\n")
