use football_domain::{competition, routing};

fn assert_same_type<T>(_: Option<T>, _: Option<T>) {}

#[test]
fn r2_02_module_paths_preserve_root_type_identity() {
    assert_same_type(
        None::<football_domain::CompetitionKind>,
        None::<competition::CompetitionKind>,
    );
    assert_same_type(
        None::<football_domain::CompetitionDraft>,
        None::<competition::CompetitionDraft>,
    );
    assert_same_type(
        None::<football_domain::CompetitionRecord>,
        None::<competition::CompetitionRecord>,
    );
    assert_same_type(
        None::<football_domain::CompetitionProfile>,
        None::<competition::CompetitionProfile>,
    );
    assert_same_type(
        None::<football_domain::SeasonDraft>,
        None::<competition::SeasonDraft>,
    );
    assert_same_type(
        None::<football_domain::SeasonRecord>,
        None::<competition::SeasonRecord>,
    );
    assert_same_type(
        None::<football_domain::SeasonTeamMembershipOption>,
        None::<competition::SeasonTeamMembershipOption>,
    );
    assert_same_type(
        None::<football_domain::StageDraft>,
        None::<competition::StageDraft>,
    );
    assert_same_type(
        None::<football_domain::StageRecord>,
        None::<competition::StageRecord>,
    );
    assert_same_type(
        None::<football_domain::RoundDraft>,
        None::<competition::RoundDraft>,
    );
    assert_same_type(
        None::<football_domain::RoundRecord>,
        None::<competition::RoundRecord>,
    );
    assert_same_type(
        None::<football_domain::RuleSourceReference>,
        None::<competition::RuleSourceReference>,
    );
    assert_same_type(
        None::<football_domain::RulePackageDraft>,
        None::<competition::RulePackageDraft>,
    );
    assert_same_type(
        None::<football_domain::RulePackageSummary>,
        None::<competition::RulePackageSummary>,
    );
    assert_same_type(
        None::<football_domain::ModelIdentity>,
        None::<routing::ModelIdentity>,
    );
    assert_same_type(
        None::<football_domain::RuleRouting>,
        None::<routing::RuleRouting>,
    );
    assert_same_type(
        None::<football_domain::CompetitionBindingDraft>,
        None::<routing::CompetitionBindingDraft>,
    );
    assert_same_type(
        None::<football_domain::CompetitionBindingSummary>,
        None::<routing::CompetitionBindingSummary>,
    );
    assert_same_type(
        None::<football_domain::ResolvedCompetitionContext>,
        None::<routing::ResolvedCompetitionContext>,
    );
    assert_same_type(
        None::<football_domain::RouteRequest>,
        None::<routing::RouteRequest>,
    );
    assert_same_type(
        None::<football_domain::RouteSource>,
        None::<routing::RouteSource>,
    );
    assert_same_type(
        None::<football_domain::RouteDecision>,
        None::<routing::RouteDecision>,
    );
}
