use football_domain::{
    coach, competition, formation, lineup, match_record, player, prediction, research, routing,
    shared, team,
};

fn assert_same_type<T>(_: Option<T>, _: Option<T>) {}

#[test]
fn r2_02_module_paths_preserve_root_type_identity() {
    assert_same_type(
        None::<football_domain::CompetitionKind>,
        None::<competition::CompetitionKind>,
    );
    assert_same_type(
        None::<football_domain::CompetitionDraft>,
        None::<competition::CompetitionDraft>,
    );
    assert_same_type(
        None::<football_domain::CompetitionRecord>,
        None::<competition::CompetitionRecord>,
    );
    assert_same_type(
        None::<football_domain::CompetitionProfile>,
        None::<competition::CompetitionProfile>,
    );
    assert_same_type(
        None::<football_domain::SeasonDraft>,
        None::<competition::SeasonDraft>,
    );
    assert_same_type(
        None::<football_domain::SeasonRecord>,
        None::<competition::SeasonRecord>,
    );
    assert_same_type(
        None::<football_domain::SeasonTeamMembershipOption>,
        None::<competition::SeasonTeamMembershipOption>,
    );
    assert_same_type(
        None::<football_domain::StageDraft>,
        None::<competition::StageDraft>,
    );
    assert_same_type(
        None::<football_domain::StageRecord>,
        None::<competition::StageRecord>,
    );
    assert_same_type(
        None::<football_domain::RoundDraft>,
        None::<competition::RoundDraft>,
    );
    assert_same_type(
        None::<football_domain::RoundRecord>,
        None::<competition::RoundRecord>,
    );
    assert_same_type(
        None::<football_domain::RuleSourceReference>,
        None::<competition::RuleSourceReference>,
    );
    assert_same_type(
        None::<football_domain::RulePackageDraft>,
        None::<competition::RulePackageDraft>,
    );
    assert_same_type(
        None::<football_domain::RulePackageSummary>,
        None::<competition::RulePackageSummary>,
    );
    assert_same_type(
        None::<football_domain::ModelIdentity>,
        None::<routing::ModelIdentity>,
    );
    assert_same_type(
        None::<football_domain::RuleRouting>,
        None::<routing::RuleRouting>,
    );
    assert_same_type(
        None::<football_domain::CompetitionBindingDraft>,
        None::<routing::CompetitionBindingDraft>,
    );
    assert_same_type(
        None::<football_domain::CompetitionBindingSummary>,
        None::<routing::CompetitionBindingSummary>,
    );
    assert_same_type(
        None::<football_domain::ResolvedCompetitionContext>,
        None::<routing::ResolvedCompetitionContext>,
    );
    assert_same_type(
        None::<football_domain::RouteRequest>,
        None::<routing::RouteRequest>,
    );
    assert_same_type(
        None::<football_domain::RouteSource>,
        None::<routing::RouteSource>,
    );
    assert_same_type(
        None::<football_domain::RouteDecision>,
        None::<routing::RouteDecision>,
    );
}

#[test]
fn r2_03_module_paths_preserve_root_type_identity() {
    assert_same_type(
        None::<football_domain::AbilityDimensionRecord>,
        None::<shared::AbilityDimensionRecord>,
    );
    assert_same_type(
        None::<football_domain::BulkArchiveFailedItem>,
        None::<shared::BulkArchiveFailedItem>,
    );
    assert_same_type(
        None::<football_domain::BulkArchiveResult>,
        None::<shared::BulkArchiveResult>,
    );
    assert_same_type(
        None::<football_domain::BulkDeleteBlockedItem>,
        None::<shared::BulkDeleteBlockedItem>,
    );
    assert_same_type(
        None::<football_domain::BulkDeleteResult>,
        None::<shared::BulkDeleteResult>,
    );
    assert_same_type(
        None::<football_domain::DataProviderDraft>,
        None::<shared::DataProviderDraft>,
    );
    assert_same_type(
        None::<football_domain::DataProviderRecord>,
        None::<shared::DataProviderRecord>,
    );
    assert_same_type(
        None::<football_domain::EntityDeletionCheck>,
        None::<shared::EntityDeletionCheck>,
    );
    assert_same_type(
        None::<football_domain::EntityMatchCandidate>,
        None::<shared::EntityMatchCandidate>,
    );
    assert_same_type(
        None::<football_domain::EntityMatchRequest>,
        None::<shared::EntityMatchRequest>,
    );
    assert_same_type(
        None::<football_domain::EntityMatchResult>,
        None::<shared::EntityMatchResult>,
    );
    assert_same_type(
        None::<football_domain::EntityReferenceCount>,
        None::<shared::EntityReferenceCount>,
    );
    assert_same_type(
        None::<football_domain::EntityReferenceQuery>,
        None::<shared::EntityReferenceQuery>,
    );
    assert_same_type(
        None::<football_domain::EntityReferenceRecord>,
        None::<shared::EntityReferenceRecord>,
    );
    assert_same_type(
        None::<football_domain::ExternalEntityIdDraft>,
        None::<shared::ExternalEntityIdDraft>,
    );
    assert_same_type(
        None::<football_domain::ExternalEntityIdRecord>,
        None::<shared::ExternalEntityIdRecord>,
    );
    assert_same_type(
        None::<football_domain::PositionReference>,
        None::<shared::PositionReference>,
    );
    assert_same_type(
        None::<football_domain::TeamDetail>,
        None::<team::TeamDetail>,
    );
    assert_same_type(None::<football_domain::TeamDraft>, None::<team::TeamDraft>);
    assert_same_type(
        None::<football_domain::TeamForceDeletePreview>,
        None::<team::TeamForceDeletePreview>,
    );
    assert_same_type(
        None::<football_domain::TeamForceDeleteRequest>,
        None::<team::TeamForceDeleteRequest>,
    );
    assert_same_type(
        None::<football_domain::TeamForceDeleteResult>,
        None::<team::TeamForceDeleteResult>,
    );
    assert_same_type(
        None::<football_domain::TeamListItem>,
        None::<team::TeamListItem>,
    );
    assert_same_type(
        None::<football_domain::TeamListPage>,
        None::<team::TeamListPage>,
    );
    assert_same_type(
        None::<football_domain::TeamListQuery>,
        None::<team::TeamListQuery>,
    );
    assert_same_type(
        None::<football_domain::TeamNameDraft>,
        None::<team::TeamNameDraft>,
    );
    assert_same_type(
        None::<football_domain::TeamNameRecord>,
        None::<team::TeamNameRecord>,
    );
    assert_same_type(
        None::<football_domain::TeamOption>,
        None::<team::TeamOption>,
    );
    assert_same_type(
        None::<football_domain::TeamPlayerPeriodRecord>,
        None::<team::TeamPlayerPeriodRecord>,
    );
    assert_same_type(
        None::<football_domain::TeamProfileDraft>,
        None::<team::TeamProfileDraft>,
    );
    assert_same_type(
        None::<football_domain::TeamProfileRecord>,
        None::<team::TeamProfileRecord>,
    );
    assert_same_type(
        None::<football_domain::TeamRecentMatch>,
        None::<team::TeamRecentMatch>,
    );
    assert_same_type(
        None::<football_domain::TeamRecord>,
        None::<team::TeamRecord>,
    );
    assert_same_type(
        None::<football_domain::TeamSquadPlayer>,
        None::<team::TeamSquadPlayer>,
    );
    assert_same_type(
        None::<football_domain::AvailabilityStatus>,
        None::<player::AvailabilityStatus>,
    );
    assert_same_type(
        None::<football_domain::PlayerAbilityObservationDraft>,
        None::<player::PlayerAbilityObservationDraft>,
    );
    assert_same_type(
        None::<football_domain::PlayerAbilityObservationRecord>,
        None::<player::PlayerAbilityObservationRecord>,
    );
    assert_same_type(
        None::<football_domain::PlayerAbilityProfile>,
        None::<player::PlayerAbilityProfile>,
    );
    assert_same_type(
        None::<football_domain::PlayerAvailabilityDraft>,
        None::<player::PlayerAvailabilityDraft>,
    );
    assert_same_type(
        None::<football_domain::PlayerAvailabilityRecord>,
        None::<player::PlayerAvailabilityRecord>,
    );
    assert_same_type(
        None::<football_domain::PlayerCatalogReferenceData>,
        None::<player::PlayerCatalogReferenceData>,
    );
    assert_same_type(
        None::<football_domain::PlayerDetail>,
        None::<player::PlayerDetail>,
    );
    assert_same_type(
        None::<football_domain::PlayerDraft>,
        None::<player::PlayerDraft>,
    );
    assert_same_type(
        None::<football_domain::PlayerListItem>,
        None::<player::PlayerListItem>,
    );
    assert_same_type(
        None::<football_domain::PlayerListPage>,
        None::<player::PlayerListPage>,
    );
    assert_same_type(
        None::<football_domain::PlayerListQuery>,
        None::<player::PlayerListQuery>,
    );
    assert_same_type(
        None::<football_domain::PlayerNameDraft>,
        None::<player::PlayerNameDraft>,
    );
    assert_same_type(
        None::<football_domain::PlayerNameRecord>,
        None::<player::PlayerNameRecord>,
    );
    assert_same_type(
        None::<football_domain::PlayerPositionDraft>,
        None::<player::PlayerPositionDraft>,
    );
    assert_same_type(
        None::<football_domain::PlayerPositionRecord>,
        None::<player::PlayerPositionRecord>,
    );
    assert_same_type(
        None::<football_domain::PlayerRecord>,
        None::<player::PlayerRecord>,
    );
    assert_same_type(
        None::<football_domain::PlayerStatus>,
        None::<player::PlayerStatus>,
    );
    assert_same_type(
        None::<football_domain::PlayerTeamPeriodDraft>,
        None::<player::PlayerTeamPeriodDraft>,
    );
    assert_same_type(
        None::<football_domain::PlayerTeamPeriodRecord>,
        None::<player::PlayerTeamPeriodRecord>,
    );
    assert_same_type(
        None::<football_domain::PreferredFoot>,
        None::<player::PreferredFoot>,
    );
    assert_same_type(
        None::<football_domain::CoachDetail>,
        None::<coach::CoachDetail>,
    );
    assert_same_type(
        None::<football_domain::CoachDraft>,
        None::<coach::CoachDraft>,
    );
    assert_same_type(
        None::<football_domain::CoachListItem>,
        None::<coach::CoachListItem>,
    );
    assert_same_type(
        None::<football_domain::CoachListQuery>,
        None::<coach::CoachListQuery>,
    );
    assert_same_type(
        None::<football_domain::CoachNameDraft>,
        None::<coach::CoachNameDraft>,
    );
    assert_same_type(
        None::<football_domain::CoachNameRecord>,
        None::<coach::CoachNameRecord>,
    );
    assert_same_type(
        None::<football_domain::CoachRecord>,
        None::<coach::CoachRecord>,
    );
    assert_same_type(
        None::<football_domain::TeamCoachPeriodDraft>,
        None::<coach::TeamCoachPeriodDraft>,
    );
    assert_same_type(
        None::<football_domain::TeamCoachPeriodRecord>,
        None::<coach::TeamCoachPeriodRecord>,
    );
    assert_same_type(
        None::<football_domain::FormationDistributionQuery>,
        None::<formation::FormationDistributionQuery>,
    );
    assert_same_type(
        None::<football_domain::FormationRecord>,
        None::<formation::FormationRecord>,
    );
    assert_same_type(
        None::<football_domain::FormationUsageDistributionDraft>,
        None::<formation::FormationUsageDistributionDraft>,
    );
    assert_same_type(
        None::<football_domain::FormationUsageDistributionRecord>,
        None::<formation::FormationUsageDistributionRecord>,
    );
    assert_same_type(
        None::<football_domain::FormationUsageEntryDraft>,
        None::<formation::FormationUsageEntryDraft>,
    );
    assert_same_type(
        None::<football_domain::FormationUsageEntryRecord>,
        None::<formation::FormationUsageEntryRecord>,
    );
    assert_same_type(
        None::<football_domain::FormationUsageListQuery>,
        None::<formation::FormationUsageListQuery>,
    );
    assert_same_type(
        None::<football_domain::ResolvedFormationDistribution>,
        None::<formation::ResolvedFormationDistribution>,
    );
}

#[test]
fn r2_04_module_paths_preserve_root_type_identity() {
    assert_same_type(
        None::<football_domain::MatchStatus>,
        None::<match_record::MatchStatus>,
    );
    assert_same_type(
        None::<football_domain::MatchDraft>,
        None::<match_record::MatchDraft>,
    );
    assert_same_type(
        None::<football_domain::MatchRecord>,
        None::<match_record::MatchRecord>,
    );
    assert_same_type(
        None::<football_domain::LineupType>,
        None::<lineup::LineupType>,
    );
    assert_same_type(
        None::<football_domain::LineupPlayerDraft>,
        None::<lineup::LineupPlayerDraft>,
    );
    assert_same_type(
        None::<football_domain::LineupPlayerRecord>,
        None::<lineup::LineupPlayerRecord>,
    );
    assert_same_type(
        None::<football_domain::LineupDraft>,
        None::<lineup::LineupDraft>,
    );
    assert_same_type(
        None::<football_domain::LineupPairDraft>,
        None::<lineup::LineupPairDraft>,
    );
    assert_same_type(
        None::<football_domain::LineupPairRecord>,
        None::<lineup::LineupPairRecord>,
    );
    assert_same_type(
        None::<football_domain::LineupRecord>,
        None::<lineup::LineupRecord>,
    );
    assert_same_type(
        None::<football_domain::LineupHistoryRemovalResult>,
        None::<lineup::LineupHistoryRemovalResult>,
    );
    assert_same_type(
        None::<football_domain::TeamLineupPresetMemberDraft>,
        None::<lineup::TeamLineupPresetMemberDraft>,
    );
    assert_same_type(
        None::<football_domain::TeamLineupPresetDraft>,
        None::<lineup::TeamLineupPresetDraft>,
    );
    assert_same_type(
        None::<football_domain::TeamLineupPresetMemberRecord>,
        None::<lineup::TeamLineupPresetMemberRecord>,
    );
    assert_same_type(
        None::<football_domain::TeamLineupPresetRecord>,
        None::<lineup::TeamLineupPresetRecord>,
    );
    assert_same_type(
        None::<football_domain::TeamLineupPresetApplicationPreview>,
        None::<lineup::TeamLineupPresetApplicationPreview>,
    );
    assert_same_type(
        None::<football_domain::MatchLineupTeamChain>,
        None::<lineup::MatchLineupTeamChain>,
    );
    assert_same_type(
        None::<football_domain::MatchLineupChain>,
        None::<lineup::MatchLineupChain>,
    );
    assert_same_type(
        None::<football_domain::TeamMatchLineupHistoryItem>,
        None::<lineup::TeamMatchLineupHistoryItem>,
    );
}

#[test]
fn r2_05_prediction_module_paths_preserve_root_type_identity() {
    assert_same_type(
        None::<football_domain::CompetitionProfileVersionDraft>,
        None::<prediction::CompetitionProfileVersionDraft>,
    );
    assert_same_type(
        None::<football_domain::CompetitionProfileVersionRecord>,
        None::<prediction::CompetitionProfileVersionRecord>,
    );
    assert_same_type(
        None::<football_domain::EvidenceClaimDraft>,
        None::<prediction::EvidenceClaimDraft>,
    );
    assert_same_type(
        None::<football_domain::EvidenceClaimRecord>,
        None::<prediction::EvidenceClaimRecord>,
    );
    assert_same_type(
        None::<football_domain::EvidenceConflictDraft>,
        None::<prediction::EvidenceConflictDraft>,
    );
    assert_same_type(
        None::<football_domain::EvidenceConflictRecord>,
        None::<prediction::EvidenceConflictRecord>,
    );
    assert_same_type(
        None::<football_domain::EvidenceVerificationState>,
        None::<prediction::EvidenceVerificationState>,
    );
    assert_same_type(
        None::<football_domain::MatchContext>,
        None::<prediction::MatchContext>,
    );
    assert_same_type(
        None::<football_domain::MatchPredictionReadiness>,
        None::<prediction::MatchPredictionReadiness>,
    );
    assert_same_type(
        None::<football_domain::P4ConflictWorkspaceRecord>,
        None::<prediction::P4ConflictWorkspaceRecord>,
    );
    assert_same_type(
        None::<football_domain::P4EvidenceWorkspaceRecord>,
        None::<prediction::P4EvidenceWorkspaceRecord>,
    );
    assert_same_type(
        None::<football_domain::P4FreezeReadiness>,
        None::<prediction::P4FreezeReadiness>,
    );
    assert_same_type(
        None::<football_domain::P4FreezeTaskDraft>,
        None::<prediction::P4FreezeTaskDraft>,
    );
    assert_same_type(
        None::<football_domain::P4FreezeTaskEventRecord>,
        None::<prediction::P4FreezeTaskEventRecord>,
    );
    assert_same_type(
        None::<football_domain::P4FreezeTaskRecord>,
        None::<prediction::P4FreezeTaskRecord>,
    );
    assert_same_type(
        None::<football_domain::P4FreezeTaskState>,
        None::<prediction::P4FreezeTaskState>,
    );
    assert_same_type(
        None::<football_domain::P4FreezeTaskTransition>,
        None::<prediction::P4FreezeTaskTransition>,
    );
    assert_same_type(
        None::<football_domain::P4Horizon>,
        None::<prediction::P4Horizon>,
    );
    assert_same_type(
        None::<football_domain::P4ManualConflictDecisionKind>,
        None::<prediction::P4ManualConflictDecisionKind>,
    );
    assert_same_type(
        None::<football_domain::P4ManualRouteOverrideDraft>,
        None::<prediction::P4ManualRouteOverrideDraft>,
    );
    assert_same_type(
        None::<football_domain::P4ManualRouteOverrideRecord>,
        None::<prediction::P4ManualRouteOverrideRecord>,
    );
    assert_same_type(
        None::<football_domain::P4MatchWorkspace>,
        None::<prediction::P4MatchWorkspace>,
    );
    assert_same_type(
        None::<football_domain::P4PlanningMatchContext>,
        None::<prediction::P4PlanningMatchContext>,
    );
    assert_same_type(
        None::<football_domain::P4ResearchRunWorkspace>,
        None::<prediction::P4ResearchRunWorkspace>,
    );
    assert_same_type(
        None::<football_domain::P4RoutedFact>,
        None::<prediction::P4RoutedFact>,
    );
    assert_same_type(
        None::<football_domain::P4TaskWorkspace>,
        None::<prediction::P4TaskWorkspace>,
    );
    assert_same_type(
        None::<football_domain::PersistedModelRun>,
        None::<prediction::PersistedModelRun>,
    );
    assert_same_type(
        None::<football_domain::PlanP4HorizonsCommand>,
        None::<prediction::PlanP4HorizonsCommand>,
    );
    assert_same_type(
        None::<football_domain::PredictionInputAuditSummary>,
        None::<prediction::PredictionInputAuditSummary>,
    );
    assert_same_type(
        None::<football_domain::PredictionReadinessCheck>,
        None::<prediction::PredictionReadinessCheck>,
    );
    assert_same_type(
        None::<football_domain::PredictionReadinessCheckStatus>,
        None::<prediction::PredictionReadinessCheckStatus>,
    );
    assert_same_type(
        None::<football_domain::PredictionReadinessLevel>,
        None::<prediction::PredictionReadinessLevel>,
    );
    assert_same_type(
        None::<football_domain::PredictionSummary>,
        None::<prediction::PredictionSummary>,
    );
    assert_same_type(
        None::<football_domain::PrematchSnapshotBundle>,
        None::<prediction::PrematchSnapshotBundle>,
    );
    assert_same_type(
        None::<football_domain::PrematchSnapshotDraft>,
        None::<prediction::PrematchSnapshotDraft>,
    );
    assert_same_type(
        None::<football_domain::PrematchSnapshotRecord>,
        None::<prediction::PrematchSnapshotRecord>,
    );
    assert_same_type(
        None::<football_domain::PromptVersionDraft>,
        None::<prediction::PromptVersionDraft>,
    );
    assert_same_type(
        None::<football_domain::PromptVersionRecord>,
        None::<prediction::PromptVersionRecord>,
    );
    assert_same_type(
        None::<football_domain::ResearchRunDraft>,
        None::<prediction::ResearchRunDraft>,
    );
    assert_same_type(
        None::<football_domain::ResearchRunEventDraft>,
        None::<prediction::ResearchRunEventDraft>,
    );
    assert_same_type(
        None::<football_domain::ResearchRunRecord>,
        None::<prediction::ResearchRunRecord>,
    );
    assert_same_type(
        None::<football_domain::ResearchRunStatus>,
        None::<prediction::ResearchRunStatus>,
    );
    assert_same_type(
        None::<football_domain::ResolveP4ConflictCommand>,
        None::<prediction::ResolveP4ConflictCommand>,
    );
    assert_same_type(
        None::<football_domain::SchemaVersionDraft>,
        None::<prediction::SchemaVersionDraft>,
    );
    assert_same_type(
        None::<football_domain::SchemaVersionRecord>,
        None::<prediction::SchemaVersionRecord>,
    );
    assert_same_type(
        None::<football_domain::SnapshotFeatureDraft>,
        None::<prediction::SnapshotFeatureDraft>,
    );
    assert_same_type(
        None::<football_domain::SnapshotProbabilityDraft>,
        None::<prediction::SnapshotProbabilityDraft>,
    );
    assert_same_type(
        None::<football_domain::SnapshotSourceKind>,
        None::<prediction::SnapshotSourceKind>,
    );
}

#[test]
fn r2_05_research_module_paths_preserve_root_type_identity() {
    assert_same_type(
        None::<football_domain::ConflictEvaluationDraft>,
        None::<research::ConflictEvaluationDraft>,
    );
    assert_same_type(
        None::<football_domain::ConflictEvaluationRecord>,
        None::<research::ConflictEvaluationRecord>,
    );
    assert_same_type(
        None::<football_domain::ConflictEvaluationStatus>,
        None::<research::ConflictEvaluationStatus>,
    );
    assert_same_type(
        None::<football_domain::EntityCandidate>,
        None::<research::EntityCandidate>,
    );
    assert_same_type(
        None::<football_domain::EntityResolutionDraft>,
        None::<research::EntityResolutionDraft>,
    );
    assert_same_type(
        None::<football_domain::EntityResolutionRecord>,
        None::<research::EntityResolutionRecord>,
    );
    assert_same_type(
        None::<football_domain::EntityResolutionStatus>,
        None::<research::EntityResolutionStatus>,
    );
    assert_same_type(
        None::<football_domain::EvidenceRouteDraft>,
        None::<research::EvidenceRouteDraft>,
    );
    assert_same_type(
        None::<football_domain::EvidenceRouteRecord>,
        None::<research::EvidenceRouteRecord>,
    );
    assert_same_type(
        None::<football_domain::EvidenceRouteRegistry>,
        None::<research::EvidenceRouteRegistry>,
    );
    assert_same_type(
        None::<football_domain::EvidenceRouteRule>,
        None::<research::EvidenceRouteRule>,
    );
    assert_same_type(
        None::<football_domain::EvidenceRouteStatus>,
        None::<research::EvidenceRouteStatus>,
    );
    assert_same_type(
        None::<football_domain::FactPipelineContext>,
        None::<research::FactPipelineContext>,
    );
    assert_same_type(
        None::<football_domain::FactPipelineSummary>,
        None::<research::FactPipelineSummary>,
    );
    assert_same_type(
        None::<football_domain::OpenAiAttemptDraft>,
        None::<research::OpenAiAttemptDraft>,
    );
    assert_same_type(
        None::<football_domain::OpenAiAttemptRecord>,
        None::<research::OpenAiAttemptRecord>,
    );
    assert_same_type(
        None::<football_domain::OpenAiUsageTotals>,
        None::<research::OpenAiUsageTotals>,
    );
    assert_same_type(
        None::<football_domain::SourcePolicyDefinition>,
        None::<research::SourcePolicyDefinition>,
    );
    assert_same_type(
        None::<football_domain::SourcePolicyVersionDraft>,
        None::<research::SourcePolicyVersionDraft>,
    );
    assert_same_type(
        None::<football_domain::SourcePolicyVersionRecord>,
        None::<research::SourcePolicyVersionRecord>,
    );
    assert_same_type(
        None::<football_domain::SourceTierDefinition>,
        None::<research::SourceTierDefinition>,
    );
    assert_same_type(
        None::<football_domain::SourceTierRule>,
        None::<research::SourceTierRule>,
    );
    assert_same_type(
        None::<football_domain::TimeAuditDraft>,
        None::<research::TimeAuditDraft>,
    );
    assert_same_type(
        None::<football_domain::TimeAuditRecord>,
        None::<research::TimeAuditRecord>,
    );
    assert_same_type(
        None::<football_domain::TimeAuditStatus>,
        None::<research::TimeAuditStatus>,
    );
    assert_same_type(
        None::<football_domain::WebCitationDraft>,
        None::<research::WebCitationDraft>,
    );
    assert_same_type(
        None::<football_domain::WebSourceDraft>,
        None::<research::WebSourceDraft>,
    );
}
