use football_domain::{coach, competition, formation, player, routing, shared, team};

fn assert_same_type<T>(_: Option<T>, _: Option<T>) {}

#[test]
fn r2_02_module_paths_preserve_root_type_identity() {
    assert_same_type(
        None::<football_domain::CompetitionKind>,
        None::<competition::CompetitionKind>,
    );
    assert_same_type(
        None::<football_domain::CompetitionDraft>,
        None::<competition::CompetitionDraft>,
    );
    assert_same_type(
        None::<football_domain::CompetitionRecord>,
        None::<competition::CompetitionRecord>,
    );
    assert_same_type(
        None::<football_domain::CompetitionProfile>,
        None::<competition::CompetitionProfile>,
    );
    assert_same_type(
        None::<football_domain::SeasonDraft>,
        None::<competition::SeasonDraft>,
    );
    assert_same_type(
        None::<football_domain::SeasonRecord>,
        None::<competition::SeasonRecord>,
    );
    assert_same_type(
        None::<football_domain::SeasonTeamMembershipOption>,
        None::<competition::SeasonTeamMembershipOption>,
    );
    assert_same_type(
        None::<football_domain::StageDraft>,
        None::<competition::StageDraft>,
    );
    assert_same_type(
        None::<football_domain::StageRecord>,
        None::<competition::StageRecord>,
    );
    assert_same_type(
        None::<football_domain::RoundDraft>,
        None::<competition::RoundDraft>,
    );
    assert_same_type(
        None::<football_domain::RoundRecord>,
        None::<competition::RoundRecord>,
    );
    assert_same_type(
        None::<football_domain::RuleSourceReference>,
        None::<competition::RuleSourceReference>,
    );
    assert_same_type(
        None::<football_domain::RulePackageDraft>,
        None::<competition::RulePackageDraft>,
    );
    assert_same_type(
        None::<football_domain::RulePackageSummary>,
        None::<competition::RulePackageSummary>,
    );
    assert_same_type(
        None::<football_domain::ModelIdentity>,
        None::<routing::ModelIdentity>,
    );
    assert_same_type(
        None::<football_domain::RuleRouting>,
        None::<routing::RuleRouting>,
    );
    assert_same_type(
        None::<football_domain::CompetitionBindingDraft>,
        None::<routing::CompetitionBindingDraft>,
    );
    assert_same_type(
        None::<football_domain::CompetitionBindingSummary>,
        None::<routing::CompetitionBindingSummary>,
    );
    assert_same_type(
        None::<football_domain::ResolvedCompetitionContext>,
        None::<routing::ResolvedCompetitionContext>,
    );
    assert_same_type(
        None::<football_domain::RouteRequest>,
        None::<routing::RouteRequest>,
    );
    assert_same_type(
        None::<football_domain::RouteSource>,
        None::<routing::RouteSource>,
    );
    assert_same_type(
        None::<football_domain::RouteDecision>,
        None::<routing::RouteDecision>,
    );
}

#[test]
fn r2_03_module_paths_preserve_root_type_identity() {
    assert_same_type(
        None::<football_domain::AbilityDimensionRecord>,
        None::<shared::AbilityDimensionRecord>,
    );
    assert_same_type(
        None::<football_domain::BulkArchiveFailedItem>,
        None::<shared::BulkArchiveFailedItem>,
    );
    assert_same_type(
        None::<football_domain::BulkArchiveResult>,
        None::<shared::BulkArchiveResult>,
    );
    assert_same_type(
        None::<football_domain::BulkDeleteBlockedItem>,
        None::<shared::BulkDeleteBlockedItem>,
    );
    assert_same_type(
        None::<football_domain::BulkDeleteResult>,
        None::<shared::BulkDeleteResult>,
    );
    assert_same_type(
        None::<football_domain::DataProviderDraft>,
        None::<shared::DataProviderDraft>,
    );
    assert_same_type(
        None::<football_domain::DataProviderRecord>,
        None::<shared::DataProviderRecord>,
    );
    assert_same_type(
        None::<football_domain::EntityDeletionCheck>,
        None::<shared::EntityDeletionCheck>,
    );
    assert_same_type(
        None::<football_domain::EntityMatchCandidate>,
        None::<shared::EntityMatchCandidate>,
    );
    assert_same_type(
        None::<football_domain::EntityMatchRequest>,
        None::<shared::EntityMatchRequest>,
    );
    assert_same_type(
        None::<football_domain::EntityMatchResult>,
        None::<shared::EntityMatchResult>,
    );
    assert_same_type(
        None::<football_domain::EntityReferenceCount>,
        None::<shared::EntityReferenceCount>,
    );
    assert_same_type(
        None::<football_domain::EntityReferenceQuery>,
        None::<shared::EntityReferenceQuery>,
    );
    assert_same_type(
        None::<football_domain::EntityReferenceRecord>,
        None::<shared::EntityReferenceRecord>,
    );
    assert_same_type(
        None::<football_domain::ExternalEntityIdDraft>,
        None::<shared::ExternalEntityIdDraft>,
    );
    assert_same_type(
        None::<football_domain::ExternalEntityIdRecord>,
        None::<shared::ExternalEntityIdRecord>,
    );
    assert_same_type(
        None::<football_domain::PositionReference>,
        None::<shared::PositionReference>,
    );
    assert_same_type(
        None::<football_domain::TeamDetail>,
        None::<team::TeamDetail>,
    );
    assert_same_type(None::<football_domain::TeamDraft>, None::<team::TeamDraft>);
    assert_same_type(
        None::<football_domain::TeamForceDeletePreview>,
        None::<team::TeamForceDeletePreview>,
    );
    assert_same_type(
        None::<football_domain::TeamForceDeleteRequest>,
        None::<team::TeamForceDeleteRequest>,
    );
    assert_same_type(
        None::<football_domain::TeamForceDeleteResult>,
        None::<team::TeamForceDeleteResult>,
    );
    assert_same_type(
        None::<football_domain::TeamListItem>,
        None::<team::TeamListItem>,
    );
    assert_same_type(
        None::<football_domain::TeamListPage>,
        None::<team::TeamListPage>,
    );
    assert_same_type(
        None::<football_domain::TeamListQuery>,
        None::<team::TeamListQuery>,
    );
    assert_same_type(
        None::<football_domain::TeamNameDraft>,
        None::<team::TeamNameDraft>,
    );
    assert_same_type(
        None::<football_domain::TeamNameRecord>,
        None::<team::TeamNameRecord>,
    );
    assert_same_type(
        None::<football_domain::TeamOption>,
        None::<team::TeamOption>,
    );
    assert_same_type(
        None::<football_domain::TeamPlayerPeriodRecord>,
        None::<team::TeamPlayerPeriodRecord>,
    );
    assert_same_type(
        None::<football_domain::TeamProfileDraft>,
        None::<team::TeamProfileDraft>,
    );
    assert_same_type(
        None::<football_domain::TeamProfileRecord>,
        None::<team::TeamProfileRecord>,
    );
    assert_same_type(
        None::<football_domain::TeamRecentMatch>,
        None::<team::TeamRecentMatch>,
    );
    assert_same_type(
        None::<football_domain::TeamRecord>,
        None::<team::TeamRecord>,
    );
    assert_same_type(
        None::<football_domain::TeamSquadPlayer>,
        None::<team::TeamSquadPlayer>,
    );
    assert_same_type(
        None::<football_domain::AvailabilityStatus>,
        None::<player::AvailabilityStatus>,
    );
    assert_same_type(
        None::<football_domain::PlayerAbilityObservationDraft>,
        None::<player::PlayerAbilityObservationDraft>,
    );
    assert_same_type(
        None::<football_domain::PlayerAbilityObservationRecord>,
        None::<player::PlayerAbilityObservationRecord>,
    );
    assert_same_type(
        None::<football_domain::PlayerAbilityProfile>,
        None::<player::PlayerAbilityProfile>,
    );
    assert_same_type(
        None::<football_domain::PlayerAvailabilityDraft>,
        None::<player::PlayerAvailabilityDraft>,
    );
    assert_same_type(
        None::<football_domain::PlayerAvailabilityRecord>,
        None::<player::PlayerAvailabilityRecord>,
    );
    assert_same_type(
        None::<football_domain::PlayerCatalogReferenceData>,
        None::<player::PlayerCatalogReferenceData>,
    );
    assert_same_type(
        None::<football_domain::PlayerDetail>,
        None::<player::PlayerDetail>,
    );
    assert_same_type(
        None::<football_domain::PlayerDraft>,
        None::<player::PlayerDraft>,
    );
    assert_same_type(
        None::<football_domain::PlayerListItem>,
        None::<player::PlayerListItem>,
    );
    assert_same_type(
        None::<football_domain::PlayerListPage>,
        None::<player::PlayerListPage>,
    );
    assert_same_type(
        None::<football_domain::PlayerListQuery>,
        None::<player::PlayerListQuery>,
    );
    assert_same_type(
        None::<football_domain::PlayerNameDraft>,
        None::<player::PlayerNameDraft>,
    );
    assert_same_type(
        None::<football_domain::PlayerNameRecord>,
        None::<player::PlayerNameRecord>,
    );
    assert_same_type(
        None::<football_domain::PlayerPositionDraft>,
        None::<player::PlayerPositionDraft>,
    );
    assert_same_type(
        None::<football_domain::PlayerPositionRecord>,
        None::<player::PlayerPositionRecord>,
    );
    assert_same_type(
        None::<football_domain::PlayerRecord>,
        None::<player::PlayerRecord>,
    );
    assert_same_type(
        None::<football_domain::PlayerStatus>,
        None::<player::PlayerStatus>,
    );
    assert_same_type(
        None::<football_domain::PlayerTeamPeriodDraft>,
        None::<player::PlayerTeamPeriodDraft>,
    );
    assert_same_type(
        None::<football_domain::PlayerTeamPeriodRecord>,
        None::<player::PlayerTeamPeriodRecord>,
    );
    assert_same_type(
        None::<football_domain::PreferredFoot>,
        None::<player::PreferredFoot>,
    );
    assert_same_type(
        None::<football_domain::CoachDetail>,
        None::<coach::CoachDetail>,
    );
    assert_same_type(
        None::<football_domain::CoachDraft>,
        None::<coach::CoachDraft>,
    );
    assert_same_type(
        None::<football_domain::CoachListItem>,
        None::<coach::CoachListItem>,
    );
    assert_same_type(
        None::<football_domain::CoachListQuery>,
        None::<coach::CoachListQuery>,
    );
    assert_same_type(
        None::<football_domain::CoachNameDraft>,
        None::<coach::CoachNameDraft>,
    );
    assert_same_type(
        None::<football_domain::CoachNameRecord>,
        None::<coach::CoachNameRecord>,
    );
    assert_same_type(
        None::<football_domain::CoachRecord>,
        None::<coach::CoachRecord>,
    );
    assert_same_type(
        None::<football_domain::TeamCoachPeriodDraft>,
        None::<coach::TeamCoachPeriodDraft>,
    );
    assert_same_type(
        None::<football_domain::TeamCoachPeriodRecord>,
        None::<coach::TeamCoachPeriodRecord>,
    );
    assert_same_type(
        None::<football_domain::FormationDistributionQuery>,
        None::<formation::FormationDistributionQuery>,
    );
    assert_same_type(
        None::<football_domain::FormationRecord>,
        None::<formation::FormationRecord>,
    );
    assert_same_type(
        None::<football_domain::FormationUsageDistributionDraft>,
        None::<formation::FormationUsageDistributionDraft>,
    );
    assert_same_type(
        None::<football_domain::FormationUsageDistributionRecord>,
        None::<formation::FormationUsageDistributionRecord>,
    );
    assert_same_type(
        None::<football_domain::FormationUsageEntryDraft>,
        None::<formation::FormationUsageEntryDraft>,
    );
    assert_same_type(
        None::<football_domain::FormationUsageEntryRecord>,
        None::<formation::FormationUsageEntryRecord>,
    );
    assert_same_type(
        None::<football_domain::FormationUsageListQuery>,
        None::<formation::FormationUsageListQuery>,
    );
    assert_same_type(
        None::<football_domain::ResolvedFormationDistribution>,
        None::<formation::ResolvedFormationDistribution>,
    );
}
