mod commands;
mod config;
mod file_store;
mod issue_log;
mod openai_profiles;
mod runtime_log;
mod workspace_state;

use commands::AppState;
use football_application::ApplicationService;
use issue_log::IssueLogStore;
use openai_profiles::OpenAiProfileStore;
use runtime_log::RuntimeLogStore;
use std::sync::Arc;
use tauri::Manager;
use workspace_state::WorkspaceStateStore;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .setup(|app| {
            let config_dir = app
                .path()
                .app_config_dir()
                .map_err(|error| std::io::Error::other(error.to_string()))?;
            let runtime_log = Arc::new(RuntimeLogStore::discover(&config_dir));
            let _ = runtime_log.record(
                "info",
                "application",
                "application_started",
                None,
                serde_json::json!({
                    "config_directory": config_dir.display().to_string(),
                    "runtime_log_path": runtime_log.path().display().to_string(),
                    "runtime_log_relative_path": runtime_log.relative_display_path(),
                    "runtime_log_relative_directory": r".\logs",
                    "runtime_log_session_id": runtime_log.session_id(),
                }),
            );
            app.manage(AppState {
                service: Arc::new(ApplicationService::new()),
                config_path: config_dir.join("database.json"),
                issue_log: Arc::new(IssueLogStore::new(config_dir.join("issue-log.json"))),
                runtime_log,
                openai_profiles: Arc::new(OpenAiProfileStore::new(
                    config_dir.join("openai-profiles.json"),
                )),
                workspace_state: Arc::new(WorkspaceStateStore::new(
                    config_dir.join("workspace-state.json"),
                )),
                api_workspace_requests: Arc::new(tokio::sync::Mutex::new(
                    std::collections::HashMap::new(),
                )),
            });
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            commands::bootstrap,
            commands::read_workspace_state,
            commands::save_workspace_state,
            commands::clear_workspace_state,
            commands::list_api_workspace_presets,
            commands::list_api_workspace_sessions,
            commands::read_api_workspace_session,
            commands::send_api_workspace_message,
            commands::cancel_api_workspace_request,
            commands::archive_api_workspace_session,
            commands::configure_database,
            commands::disconnect_database,
            commands::reset_database,
            commands::record_issue,
            commands::record_runtime_operation,
            commands::list_issue_logs,
            commands::clear_issue_logs,
            commands::export_issue_logs,
            commands::dry_run_default_fixture,
            commands::execute_prediction,
            commands::execute_prediction_from_match,
            commands::execute_shadow_prediction_from_match,
            commands::inspect_match_prediction_readiness,
            commands::preview_route,
            commands::plan_p4_horizons,
            commands::list_p4_freeze_tasks,
            commands::read_p4_freeze_task,
            commands::list_p4_freeze_task_events,
            commands::p4_freeze_readiness,
            commands::read_p4_match_workspace,
            commands::read_p4_task_workspace,
            commands::resolve_p4_conflict,
            commands::create_competition,
            commands::delete_competition,
            commands::create_season,
            commands::create_stage,
            commands::create_round,
            commands::register_rule_package,
            commands::create_competition_binding,
            commands::list_recent_runs,
            commands::read_run,
            commands::hide_model_run_history,
            commands::list_formations,
            commands::save_formation_usage_distribution,
            commands::list_formation_usage_distributions,
            commands::resolve_formation_distribution,
            commands::player_catalog_reference_data,
            commands::create_coach,
            commands::list_coaches,
            commands::read_coach,
            commands::add_coach_name,
            commands::add_team_coach_period,
            commands::list_entity_references,
            commands::resolve_entity_reference,
            commands::check_entity_deletion,
            commands::bulk_archive_entities,
            commands::create_team,
            commands::list_team_options,
            commands::list_teams,
            commands::read_team,
            commands::update_team,
            commands::add_team_name,
            commands::upsert_team_profile,
            commands::bulk_delete_players,
            commands::bulk_delete_teams,
            commands::preview_force_delete_team,
            commands::force_delete_team,
            commands::create_data_provider,
            commands::create_player,
            commands::delete_player,
            commands::list_players,
            commands::read_player,
            commands::export_team_package_template,
            commands::export_team_package_preview_json,
            commands::preview_team_package_import,
            commands::commit_team_package_import,
            commands::export_player_catalog_template,
            commands::export_player_catalog_data,
            commands::preview_player_catalog_import,
            commands::read_player_catalog_import_preview,
            commands::resolve_player_catalog_import_conflict,
            commands::commit_player_catalog_import,
            commands::export_team_monthly_template,
            commands::export_team_monthly_data,
            commands::preview_team_monthly_import,
            commands::read_team_monthly_import_preview,
            commands::resolve_team_monthly_import_conflict,
            commands::commit_team_monthly_import,
            commands::update_player,
            commands::add_player_name,
            commands::assign_player_position,
            commands::add_player_team_period,
            commands::add_player_availability,
            commands::add_player_ability_observation,
            commands::add_external_entity_id,
            commands::create_match,
            commands::delete_match,
            commands::save_team_lineup_preset,
            commands::list_team_lineup_presets,
            commands::preview_team_lineup_preset_application,
            commands::duplicate_team_lineup_preset,
            commands::archive_team_lineup_preset,
            commands::delete_team_lineup_preset,
            commands::create_lineup,
            commands::create_lineup_pair,
            commands::list_lineups,
            commands::read_lineup,
            commands::remove_lineup_history,
            commands::read_match_lineup_chain,
            commands::list_team_match_lineups,
            commands::add_player_dynamic_tag,
            commands::calculate_player_match_contribution,
            commands::export_match_lineup_template,
            commands::export_match_lineup_data,
            commands::preview_match_lineup_import,
            commands::read_match_lineup_import_preview,
            commands::resolve_match_lineup_import_conflict,
            commands::commit_match_lineup_import,
            commands::export_ai_match_package,
            commands::preview_ai_match_package,
            commands::generate_match_review,
            commands::list_reviewable_matches,
            commands::list_match_reviews,
            commands::read_match_review,
            commands::list_ability_candidates,
            commands::decide_ability_candidate,
            commands::postmatch_settlement_readiness,
            commands::settle_postmatch_review,
            commands::list_postmatch_settlements,
            commands::list_evidence_scoring_items,
            commands::decide_evidence_scoring_item,
            commands::refresh_postmatch_monitoring,
            commands::postmatch_overview,
            commands::export_match_review_package,
            commands::preview_match_review_package,
            commands::read_match_review_package_workflow,
            commands::confirm_match_review_package,
            commands::commit_match_review_package_facts,
            commands::generate_match_review_from_package,
            commands::commit_match_review_package,
            commands::analytics_overview,
            commands::enqueue_analysis_job,
            commands::list_background_jobs,
            commands::cancel_background_job,
            commands::retry_background_job,
            commands::export_ai_analysis_package,
            commands::preview_ai_analysis_response,
            commands::import_ai_analysis_response,
            commands::list_ai_analysis_suggestions,
            commands::decide_ai_analysis_suggestion,
            commands::decide_data_quality_finding,
            commands::export_ai_analysis_response_template,
            commands::generate_parameter_tuning_candidate,
            commands::list_parameter_tuning_candidates,
            commands::decide_parameter_tuning_candidate,
            commands::parameter_lifecycle_readiness,
            commands::run_parameter_shadow_validation,
            commands::list_parameter_shadow_validations,
            commands::promote_parameter_candidate,
            commands::rollback_parameter_candidate,
            commands::list_parameter_promotion_decisions,
            commands::run_release_acceptance,
            commands::list_release_acceptance_runs,
            commands::read_release_acceptance_run,
            commands::parse_openai_api_example,
            commands::list_openai_profiles,
            commands::save_openai_profile,
            commands::set_active_openai_profile,
            commands::delete_openai_profile,
            commands::clear_openai_profile_key,
            commands::test_openai_profile,
        ])
        .run(tauri::generate_context!())
        .expect("足球赛事模型平台启动失败");
}
